services:
    homarr:
        image: ghcr.io/homarr-labs/homarr:latest
        container_name: homarr
        ports:
            - "7575:3000"
        restart: unless-stopped
        networks:
            - homelab
        volumes:
            - homarr_data:/appdata
        environment:
            SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}

networks:
    homelab:
        external: true

volumes:
    homarr_data:
        name: homarr_data
